---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

.template: &build
  stage: build
  image: vpgrp/kitchen:latest
  before_script:
    - apt-get update
    - apt-get install -t stretch-backports -y debootstrap
  artifacts:
    expire_in: 1 day
    paths:
      - image
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/debian-v7.0.tar
    - docker load -i image/debian-v8.0.tar
    - docker load -i image/debian-v9.0.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - deploy

# test
shellcheck:
  stage: test
  image: vpgrp/linter:shell
  script:
    - shellcheck build.sh

# build
v7.0:
  <<: *build
  script:
    - ./build.sh -d wheezy -v
    - mkdir image
    - docker save debian:wheezy > image/debian-v7.0.tar

v8.0:
  <<: *build
  script:
    - ./build.sh -d jessie -v
    - mkdir image
    - docker save debian:jessie > image/debian-v8.0.tar

v9.0:
  <<: *build
  script:
    - ./build.sh -d stretch -v
    - mkdir image
    - docker save debian:stretch > image/debian-v9.0.tar

# deploy
# https://hub.docker.com/u/vpgrp/
vpgrp:
  <<: *deploy
  script:
    - docker tag debian:wheezy  vpgrp/debian:wheezy
    - docker tag debian:wheezy  vpgrp/debian:7
    - docker tag debian:jessie  vpgrp/debian:jessie
    - docker tag debian:jessie  vpgrp/debian:8
    - docker tag debian:jessie  vpgrp/debian:oldstable
    - docker tag debian:stretch vpgrp/debian:stretch
    - docker tag debian:stretch vpgrp/debian:9
    - docker tag debian:stretch vpgrp/debian:stable
    - docker tag debian:stretch vpgrp/debian:latest
    - docker push vpgrp/debian:wheezy
    - docker push vpgrp/debian:7
    - docker push vpgrp/debian:jessie
    - docker push vpgrp/debian:8
    - docker push vpgrp/debian:oldstable
    - docker push vpgrp/debian:stretch
    - docker push vpgrp/debian:9
    - docker push vpgrp/debian:stable
    - docker push vpgrp/debian:latest

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag debian:wheezy  vptech/debian:wheezy
    - docker tag debian:wheezy  vptech/debian:7
    - docker tag debian:jessie  vptech/debian:jessie
    - docker tag debian:jessie  vptech/debian:8
    - docker tag debian:jessie  vptech/debian:oldstable
    - docker tag debian:stretch vptech/debian:stretch
    - docker tag debian:stretch vptech/debian:9
    - docker tag debian:stretch vptech/debian:stable
    - docker tag debian:stretch vptech/debian:latest
    - docker push vptech/debian:wheezy
    - docker push vptech/debian:7
    - docker push vptech/debian:jessie
    - docker push vptech/debian:8
    - docker push vptech/debian:oldstable
    - docker push vptech/debian:stretch
    - docker push vptech/debian:9
    - docker push vptech/debian:stable
    - docker push vptech/debian:latest
# EOF
