---

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.2
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.2.1
    file: gitlab-ci.yml

.template: &build
  stage: build
  image: docker.registry.vptech.eu/vptech/debian:buster
  before_script:
    - apt-get update  -qq -y
    - apt-get install -qq -y apt-transport-https ca-certificates curl debootstrap kmod gnupg-agent procps software-properties-common sudo systemd tar
    - ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/focal
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update  -qq -y
    - apt-get install -qq -y docker-ce docker-ce-cli containerd.io
    - env DOCKER_DRIVER=vfs dockerd &
  artifacts:
    expire_in: 1 day
    paths:
      - image
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - docker login -u "$DOCKER_PUBLIC_REGISTRY_USERNAME" -p "$DOCKER_PUBLIC_REGISTRY_PASSWORD"
    - docker load -i image/debian-v8.0.tar
    - docker load -i image/debian-v8.0-systemd.tar
    - docker load -i image/debian-v9.0.tar
    - docker load -i image/debian-v9.0-systemd.tar
    - docker load -i image/debian-v10.0.tar
    - docker load -i image/debian-v10.0-systemd.tar
  only:
    - master
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - deploy
  - release

# build
v8.0:
  <<: *build
  script:
    - ./build.sh -d jessie -v
    - mkdir image
    - docker save debian:jessie > image/debian-v8.0.tar

v8.0:systemd:
  <<: *build
  script:
    - ./build.sh -d jessie -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:jessie-systemd > image/debian-v8.0-systemd.tar

v9.0:
  <<: *build
  script:
    - ./build.sh -d stretch -v
    - mkdir image
    - docker save debian:stretch > image/debian-v9.0.tar

v9.0:systemd:
  <<: *build
  script:
    - ./build.sh -d stretch -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:stretch-systemd > image/debian-v9.0-systemd.tar

v10.0:
  <<: *build
  script:
    - ./build.sh -d buster -v
    - mkdir image
    - docker save debian:buster > image/debian-v10.0.tar

v10.0:systemd:
  <<: *build
  script:
    - ./build.sh -d buster -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:buster-systemd > image/debian-v10.0-systemd.tar

# deploy
vptech:
  <<: *deploy
  script:
    - docker tag debian:jessie          vptech/debian:jessie
    - docker tag debian:jessie          vptech/debian:8
    - docker tag debian:jessie-systemd  vptech/debian:jessie-systemd
    - docker tag debian:jessie -systemd vptech/debian:8-systemd
    - docker tag debian:stretch         vptech/debian:stretch
    - docker tag debian:stretch         vptech/debian:9
    - docker tag debian:stretch         vptech/debian:oldstable
    - docker tag debian:stretch-systemd vptech/debian:stretch-systemd
    - docker tag debian:stretch-systemd vptech/debian:9-systemd
    - docker tag debian:stretch-systemd vptech/debian:oldstable-systemd
    - docker tag debian:buster          vptech/debian:buster
    - docker tag debian:buster          vptech/debian:10
    - docker tag debian:buster          vptech/debian:stable
    - docker tag debian:buster          vptech/debian:latest
    - docker tag debian:buster-systemd  vptech/debian:buster-systemd
    - docker tag debian:buster-systemd  vptech/debian:10-systemd
    - docker tag debian:buster-systemd  vptech/debian:stable-systemd
    - docker push --all-tags vptech/debian
# EOF
