---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

.template: &build
  stage: build
  image: vptech/kitchen:latest
  before_script:
    - apt-get update
    - apt-get install -y -qq debootstrap sudo
  artifacts:
    expire_in: 1 day
    paths:
      - image
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/debian-v8.0.tar
    - docker load -i image/debian-v9.0.tar
    - docker load -i image/debian-v10.0.tar
    - docker load -i image/debian-v9.0-systemd.tar
    - docker load -i image/debian-v10.0-systemd.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - deploy

# test
shellcheck:
  stage: test
  image: vptech/linter:shell
  script:
    - shellcheck build.sh

# build
v8.0:
  <<: *build
  script:
    - ./build.sh -d jessie -v
    - mkdir image
    - docker save debian:jessie > image/debian-v8.0.tar

v9.0:
  <<: *build
  script:
    - ./build.sh -d stretch -v
    - mkdir image
    - docker save debian:stretch > image/debian-v9.0.tar

v9.0_systemd:
  <<: *build
  script:
    - ./build.sh -d stretch -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:stretch-systemd > image/debian-v9.0-systemd.tar

v10.0:
  <<: *build
  script:
    - ./build.sh -d buster -v
    - mkdir image
    - docker save debian:buster > image/debian-v10.0.tar

v10.0_systemd:
  <<: *build
  script:
    - ./build.sh -d buster -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:buster-systemd > image/debian-v10.0-systemd.tar

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag debian:jessie          vptech/debian:jessie
    - docker tag debian:jessie          vptech/debian:8
    - docker tag debian:stretch         vptech/debian:stretch
    - docker tag debian:stretch         vptech/debian:9
    - docker tag debian:stretch         vptech/debian:oldstable
    - docker tag debian:stretch-systemd vptech/debian:stretch-systemd
    - docker tag debian:stretch-systemd vptech/debian:9-systemd
    - docker tag debian:stretch-systemd vptech/debian:oldstable-systemd
    - docker tag debian:buster          vptech/debian:buster
    - docker tag debian:buster          vptech/debian:10
    - docker tag debian:buster          vptech/debian:stable
    - docker tag debian:buster          vptech/debian:latest
    - docker tag debian:buster-systemd  vptech/debian:buster-systemd
    - docker tag debian:buster-systemd  vptech/debian:10-systemd
    - docker tag debian:buster-systemd  vptech/debian:stable-systemd
    - docker push vptech/debian:jessie
    - docker push vptech/debian:8
    - docker push vptech/debian:stretch
    - docker push vptech/debian:9
    - docker push vptech/debian:oldstable
    - docker push vptech/debian:stretch-systemd
    - docker push vptech/debian:9-systemd
    - docker push vptech/debian:oldstable-systemd
    - docker push vptech/debian:buster
    - docker push vptech/debian:10
    - docker push vptech/debian:stable
    - docker push vptech/debian:buster-systemd
    - docker push vptech/debian:10-systemd
    - docker push vptech/debian:stable-systemd
    - docker push vptech/debian:latest
# EOF
